name: catcher
description: Plugin for error catching which provides multiple handlers for dealing with errors when they are not caught by the developer.
version: 0.8.0
publish_to: none
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/catcher
repository: https://github.com/jhomlala/catcher
issue_tracker: https://github.com/jhomlala/catcher/issues
topics:
  - error
  - errors
  - logs
  - devtools
  - tool

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=3.19.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_styled_toast: 
    git: https://github.com/sumitsharansatsangi/flutter_styled_toast.git
  device_info_plus:
    git: https://github.com/kumsumit/device_info_plus.git
  device_info_plus_platform_interface:
    git: https://github.com/kumsumit/device_info_plus_platform_interface.git
  package_info_plus: 
    git:  https://github.com/kumsumit/package_info_plus.git
  mailer: ^6.0.1
  dio: ^5.4.1
  flutter_mailer: 
    git: https://github.com/kumsumit/flutter_mailer.git
  logging: ^1.2.0
  sentry: 
    git: https://github.com/kumsumit/sentry.git
  universal_io: ^2.2.2
  very_good_analysis: ^5.1.0

dev_dependencies:
  lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.catcher
        pluginClass: CatcherPlugin
      ios:
        pluginClass: CatcherPlugin
      web:
        pluginClass: CatcherWebPlugin
        fileName: catcher_web_plugin.dart
      macos:
        pluginClass: CatcherPlugin
      windows:
        pluginClass: CatcherPlugin
      linux:
        pluginClass: CatcherPlugin
